from goodies import *

print(Colour.white + "    '... if you gaze long into an abyss,")
sleep(1.5)
print(Colour.grey + "     the abyss will also gaze into you.'")
sleep(3)
print()
print(Colour.white + "                   - Friedrich Nietzsche")
sleep(2)
clear()
print()
print("               Tom Smith is....")
sleep(2)
clear()
print("  __  .__                                         ")
print("_/  |_|  |__   ____  " + Colour.red + "   ____" + Colour.white + "_______  ______  _  __")
print("\   __\  |  \_/ __ \ " + Colour.red + " _/ ___\\" + Colour.white + "_  __ \/  _ \ \/ \/ /")
print(" |  | |   Y  \  ___/ " + Colour.red + " \  \___" + Colour.white + "|  | \(  <_> )     / ")
print(" |__| |___|  /\___  >" + Colour.red + "  \___  >" + Colour.white + "__|   \____/ \/\_/  ")
print("           \/     \/ " + Colour.red + "      \/                     ")
sleep(3)
clear()
print()
print()
print(Colour.red + "                     Coming soon")
sleep(0.25)
clear()
print()
print()
print(Colour.pink + "                     Coming soon")
sleep(0.25)
clear()
print()
print()
print(Colour.white + "                     Coming soon")
