from goodies import *

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.yellow + "  ` -(_)--(_)" + Colour.blue + "-' " + Colour.reset)
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "      ______")
print("     /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("    (   _    _ _\ ")
print(Colour.reset + " ===" + Colour.yellow + "  ` -(_)--(_)" + Colour.reset + "-'    ")
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "         ______")
print("        /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("       (   _    _ _\ ")
print(Colour.reset + "    === " + Colour.yellow + "  -(_)--(_)" + Colour.reset + "-'")
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "            ______")
print("           /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("          (   _    _ _\ ")
print(Colour.reset + "       === " + Colour.yellow + "` -(_)--(_)" + Colour.reset + "-' ")   
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

print("     ,.,")
print(" ('=(---)=')")
print(" '))|+_+|(('" + Colour.magenta + "  Mother : Turn that frown upside down... " + Colour.reset)
print("  ('_\-/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print(Colour.grey + Style.bold + "The sound of your mothers voice fills the car." +  Colour.reset)
sleep(2)
clear()
print("     ,.,")
print(" ('=(---)=')")
print(" '))|+_+|(('" + Colour.magenta + "  Mother : I know you're not a fan of the cousins. " + Colour.reset)
print("  ('_\./_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('" + Colour.magenta + "  Mother : But please be nice and polite to them." + Colour.reset)
print("  ('_\o/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('")
print("  ('_\_/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('" + Colour.magenta + "  Mother : Isn't that right, Dan?" + Colour.reset)
print("  ('_\-/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print("    (^^^) ")
print("    q+_+p")
print("   __\=/__ " + Colour.orange + "  Father : ..." + Colour.reset)
print("  /||___||\ ")
print(" / ||_|_|| \ ")
print(" | |  |  | | ")
print("")
sleep(3)
clear()
print("     ,.,")
print("    (^^^) ")
print("    q+_+p")
print("   __\=/__ " + Colour.orange + "  Father : Listen to your mother." + Colour.reset)
print("  /||___||\ ")
print(" / ||_|_|| \ ")
print(" | |  |  | | ")
sleep(2)
clear()




print("")
print("")
print("")
print("")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.reset + "===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")
sleep(0.5)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + " ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + " ==`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + "  =`" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + "   `" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(3)
clear()
print(Colour.grey + Style.bold + "Your mother pulls into the driveway.")
sleep(4)
clear()
print(Colour.grey + Style.bold + "You prepare yourself to enter your aunt's house...")
sleep(3)


print("       _")
print(Colour.orange + "     _" + Colour.reset + "|=|" + Colour.orange + "__________")
print("    /              \ ")
print("   /                \ ")
print("  /__________________\ " + Colour.reset)
print("   ||  || /" + Colour.red + "--" + Colour.reset + "\ ||  || ")
print("   ||[]||" + Colour.red + " | .| " + Colour.reset + "||[]||")
print(Colour.green +" ()" + Colour.reset + "||__||_" + Colour.red + "|__|" + Colour.reset + "_||__||" + Colour.green +"()")
print(Colour.green + "( )" + Colour.reset + "|-|-|-|====|-|-|-|" + Colour.green + "( )") 
print(Colour.green + "^^^^^^^^^^" + Colour.reset + "====" + Colour.green + "^^^^^^^^^^^")
print("")
sleep(3)
clear()
print(Colour.reset + Style.bold + "---------------------------------------")
print("|         TO BE CONTINUED ...         |")
print("---------------------------------------")
