# Your amazing code goes here!
from goodies import *
print()
print(Colour.grey + "                           Coming Spring This Year ...")
sleep(0.125)
clear()
print()
print(Colour.orange + "                           Coming Spring This Year...")
sleep(0.125)
clear()
print()
print(Colour.yellow + "                           Coming Spring This Year...")
sleep(0.125)
clear()
print()
print(Colour.white + "                           Coming Spring This Year...")
sleep(1)
clear()
print()
print(Colour.yellow + "                           Coming Spring This Year...")
sleep(0.125)
clear()
print()
print(Colour.orange + "                           Coming Spring This Year...")
sleep(0.125)
clear()
print()
print(Colour.grey + "                           Coming Spring This Year...")
sleep(0.125)

clear()
sleep(1.5)
print(Colour.white +      "                            Her journey concludes.")
sleep(1.5)
print(Colour.pink +       "                       Enemies defeated and friends lost")
sleep(2.5)
print(Colour.red +      "                          They cry out for revenge..")
sleep(3)

clear()
print()
print(Colour.white + "                                 Ms Smith is...")
sleep(3)


clear()
print(Colour.white + "                                                                            ,---.") 
sleep(0.06725)
print(Colour.white + ",--------.,--.  ,--.,------.     ,-----. ,-----. ,------.  ,------.,------. |   |")  
sleep(0.06725)
print(Colour.yellow + "'--.  .--'|  '--'  ||  .---'    '  .--./'  .-.  '|  .-.  \ |  .---'|  .--. '|  .'")  
sleep(0.06725)
print(Colour.orange + "   |  |   |  .--.  ||  `--,     |  |    |  | |  ||  |  \  :|  `--, |  '--'.'|  | ")  
sleep(0.06725)
print(Colour.orange + "   |  |   |  |  |  ||  `---.    '  '--'\\'  '-'  '|  '--'  /|  `---.|  |\\  \\ `--' ")  
sleep(0.06725)
print(Colour.red + "   `--'   `--'  `--'`------'     `-----' `-----' `-------' `------'`--' '--'.--. ")  
sleep(0.06725)
print(Colour.red + "                                                                            '--' ") 
sleep(3)

clear()
print()
print(Colour.grey + "                                Only in theatres")
sleep(0.25)
clear()
print()
print(Colour.orange + "                                Only in theatres")
sleep(0.25)
clear()
print()
print(Colour.yellow + "                                Only in theatres")
sleep(0.25)
clear()
print()
print(Colour.white + "                                Only in theatres")
sleep(2)
clear()
print()
print(Colour.yellow + "                                Only in theatres")
sleep(0.25)
clear()
print()
print(Colour.orange + "                                Only in theatres")
sleep(0.25)
clear()
print()
print(Colour.grey + "                                Only in theatres")
sleep(0.25)
clear()
