from goodies import playSound
input("Press [Enter] when you are ready!")
print()
playSound("samples/music/anthem.mp3")
print("Australians all let us rejoice")
sleep(5.1)
print("For we are young and free")
sleep(4.8)
print("We've golden soil and wealth for toil")
sleep(5.1)
print("Our home is girt by sea")
sleep(4.9)
print("Our land abounds in nature's gifts")
sleep(5.4)
print("Of beauty, rich and rare")
sleep(4.5)
print("In history's page let every stage")
sleep(5.19)
print("ADVANCE AUSTRALIA FAIR!")
sleep(5.2)
print()
input("Want to sing the rest of the song? Press [Enter] to subscribe for only $5.99 a month!")
print("Stay tuned for more information!")
sleep(2)