from goodies import Colour
label .menu
clear()
print("  My Virtual Dog!")
print("        __       ")
print("      o'')}_____/ ")
print("       `_/      ) ")
print("       (_(_/-(_/  ")

print("1. Feed the dog")
print("2. Pet the dog")
print("3. Quit")
option = input("Enter your choice:")
if option == "1":
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print(Colour.pink + "munch! ˁ" + Colour.white +  "_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.125)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print(Colour.pink + "munch! ˁ" + Colour.white +  "_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.5)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print(Colour.pink + "munch! ˁ" + Colour.white +  "_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)    
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)    
    goto .menu
if option == "2":
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}____\ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}____\ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}____\ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    goto .menu
if option == "5":
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print(Colour.orange + " woof!" + Colour.reset + " °_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.75)
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print(Colour.orange + " woof!" + Colour.reset + " °_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.25)
    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.125)    
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print(Colour.orange + " woof!" + Colour.reset + " °_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.35)    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.125)    
    
    clear()
    print("  My Virtual Dog!")
    print("        __       ")
    print("      o'')}_____/ ")
    print(Colour.orange + " woof!" + Colour.reset + " °_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.35)    
    clear()
    print("  My Virtual Dog!")
    print("        __        ")
    print("      o'')}_____/ ")
    print("       `_/      ) ")
    print("       (_(_/-(_/  ")
    sleep(0.125)           
    goto .menu
if option == "3":
    print(Colour.green + "Thanks for playing with me!")
    goto .end
print("Invalid option, try again.")  
sleep(2)
goto .menu

label .end
