print("First Fig by Edna St. Vincent Millay")
print()
sleep(2)
print("   My candle burns at both ends;")
print()
sleep(1.5)
print("   It will not last the night;")
print()
sleep(1.5)
print("   But ah, my foes, and oh, my friends—")
print()
sleep(1.5)
print("   It gives a lovely light!")
print()
sleep(1.5)
print("The End")