print("Facts about Australia!")
input("Press [Enter] to display a fact")
print("Australia is the only country which is also a continent.")
input("Press [Enter] to display another fact")
print("The word 'selfie' was invented in Australia!")