from csinsc import *

print(Highlight.magenta)
print("                       " + Colour.grey + "_____                       ")
print("                    ▄████████▄▄                    ")
print("                  ▄█████████████▄                  ")
print("                 ████████████████▄                 ")
print("                 ██████████████████                ")
print("                 ██████████████████                ")
print("                  ▀████████████████                ")
print("            ▄▄▄██████████████████▀                 ")
print("         █" + Highlight.white + "▀▀▀█▀     ▀" + Highlight.magenta + "██████████▀                   ")
print("       ▄" + Highlight.white + "▀_      _      ▀" + Highlight.magenta + "████████▄                  ")
print("      █" + Highlight.white + "  _`    _ `      ▀" + Highlight.magenta + "████████▄   ____          ")
print("   _  █" + Highlight.white + " /  \\  /  \\      " + Highlight.magenta + "██████████ ▄██████▄        ")
print("  ▄█▄ █" + Highlight.white + " | ▄█  | ▄█      " + Highlight.magenta + "██████████▄██████████▄     ")
print(" █████▄ \_█▀  \_█▀      ▄█████████████████████▄    ")
print(" ▄▀█▀  `'-.            ▄███████████████████████    ")
print("█          `          `      ▀█████████████████    ")
print("█                        __    ███████████████▀    ")
print(" █                       / `   ▄▀██████████▀▀      ")
print("  ▀▄▄                  .'    ██▀  ▀██████▀         ")
print("     ▀▄▄.,__    ___.-'    ▄█▀                      ")
print("         ▀▄▄▄````  ▄▄▄▄▄▄▀▀                        ")
print("             ▀▀▀▀▀▀                                ")

print(Colour.reset)