from csinsc import *

#friendly reminder
label .game_start
print("NOTE:")
sleep(1)
print("The way you enter your choices into the game is " + Style.underline + "VERY" + Colour.reset + " important.")
sleep(2)
print("please enter your choices exactly as the question displays  " + Highlight.blue + "(Capitalisation included!!)" + Colour.reset)
sleep(3)
print("")
print("Thanks! Enjoy the game.")
sleep(4)
clear()

#Title card

print("")
print("")
sleep(2)
print("")
print("            stay alive.")
sleep(2)
print(Colour.reset + "            " + Colour.red + Style.underline +"don't" + Colour.reset + "  get bit.")
sleep(4)
clear()

label .com_scene
print(Colour.red + "             _     _ _")
print("            | |   (_) |")    
print("            | |__  _| |_")   
print("            | '_ \| | __| ") 
print("            | |_) | | |__ ")
print("            |_.__/|_|\__(_)")
sleep(1)
clear()
print(Colour.red + "             _     _ _")
print("            | |   (_) |")    
print("            | |__  _| |_")   
print("            | '_ \| | __| ") 
print("            | |_) | | |__ ")
print("            |_.__/|_|\__(_)"+ Colour.reset + Style.bold + " by Emily" + Colour.reset)
sleep(3)
clear()

label .skip
#CHOICE 1, TWO ANSWERS
print("if you have " + Colour.red + "already" + Colour.reset + " played through the introduction, it may be helpful to skip the intro.")
print("Skip intro scene?")
yn = input("Yes or No :  ")
if yn == "Yes":
    clear()
    goto .nathan
    
if yn == "No":  
    clear()
    goto .carscene

clear()
print("Invalid input.")
sleep(2)
print("Try again.")
sleep(2)
goto .skip


label .carscene

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.yellow + "  ` -(_)--(_)" + Colour.blue + "-' " + Colour.reset)
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()


print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "      ______")
print("     /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("    (   _    _ _\ ")
print(Colour.reset + " ===" + Colour.yellow + "  ` -(_)--(_)" + Colour.reset + "-'    ")
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

   

print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "         ______")
print("        /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("       (   _    _ _\ ")
print(Colour.reset + "    === " + Colour.yellow + "  -(_)--(_)" + Colour.reset + "-'")
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()

 
print(Colour.green + "     ccee88oo")
print("   C8O8O8Q8PoOb o8oo")
print("  dOB69QO8PdUOpugoO9bD")
print(" CgggbU8OU qOp qOdoUOdcb")
print("     6OuU" + Colour.orange + "  /" + Colour.green + "p u gcoUodpP")
print(Colour.orange + "       \\\//  /" + Colour.green + "douUP")
print(Colour.orange + "         \\\////")
print("          |||/\ ")
print("          |||\/")
print("          |||||" + Colour.reset)
print("    ....." + Colour.orange + "//||||\ " + Colour.reset + "..........")
print(Colour.blue + "            ______")
print("           /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("          (   _    _ _\ ")
print(Colour.reset + "       === " + Colour.yellow + "` -(_)--(_)" + Colour.reset + "-' ")   
print(" ")
print(" ------------------------------------------------")
sleep(0.5)
clear()


print("     ,.,")
print(" ('=(---)=')")
print(" '))|+_+|(('" + Colour.magenta + "  Get that frown off your face. " + Colour.reset)
print("  ('_\-/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print(Colour.grey + Style.bold + "The jarring sound of your mothers voice fills the car." +  Colour.reset)
sleep(2)
clear()
print("     ,.,")
print(" ('=(---)=')")
print(" '))|+_+|(('" + Colour.magenta + "   Mother : Play nice. I know you dont like the cousins, " + Colour.reset)
print("  ('_\./_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('" + Colour.magenta + "  Mother : but You're going to have to put up with them." + Colour.reset)
print("  ('_\o/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('")
print("  ('_\_/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print(" ('=(---)=') ")
print(" '))|+_+|(('" + Colour.magenta + "   Mother : Isn't that right, dan?" + Colour.reset)
print("  ('_\-/_')")
print("  /||___||\ ")
print(" /,||_|_||,\ ")
print(" \_|  |  |_/ ")
sleep(3)
clear()
print("     ,.,")
print("    (^^^) ")
print("    q+_+p")
print("   __\=/__ " + Colour.orange + "  ..." + Colour.reset)
print("  /||___||\ ")
print(" / ||_|_|| \ ")
print(" | |  |  | | ")
print("")
sleep(3)
clear()
print("     ,.,")
print("    (^^^) ")
print("    q+_+p")
print("   __\=/__ " + Colour.orange + "  Father : listen to your mother." + Colour.reset)
print("  /||___||\ ")
print(" / ||_|_|| \ ")
print(" | |  |  | | ")
sleep(2)
clear()




print("")
print("")
print("")
print("")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.reset + "===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")
sleep(0.5)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + " ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + " ==`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + "  =`" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

sleep(0.5)
clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + "   `" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("----------------------/")

 

sleep(3)
clear()
print(Colour.grey + Style.bold + "Your mother pulls into the driveway.")
sleep(4)
clear()
print(Colour.grey + Style.bold + "A familiar sense of dread comes upon you.")
sleep(3)
clear()
print(Colour.grey + Style.bold + "you prepare yourself...")
sleep(3)
clear()
print(Colour.grey + Style.bold + "And enter your aunts house.")
sleep(2)
clear()
print(Colour.grey + Style.bold + "Family reunions  " + Style.underline + "suck." + Colour.reset)
sleep(4)
clear()



print("       _")
print(Colour.orange + "     _" + Colour.reset + "|=|" + Colour.orange + "__________")
print("    /              \ ")
print("   /                \ ")
print("  /__________________\ " + Colour.reset)
print("   ||  || /" + Colour.red + "--" + Colour.reset + "\ ||  || ")
print("   ||[]||" + Colour.red + " | .| " + Colour.reset + "||[]||")
print(Colour.green +" ()" + Colour.reset + "||__||_" + Colour.red + "|__|" + Colour.reset + "_||__||" + Colour.green +"()")
print(Colour.green + "( )" + Colour.reset + "|-|-|-|====|-|-|-|" + Colour.green + "( )") 
print(Colour.green + "^^^^^^^^^^" + Colour.reset + "====" + Colour.green + "^^^^^^^^^^^")
print("")
sleep(2)
clear()
print(Colour.grey + Style.bold + "The white picket fence lines the gates to your own personal hell.")
print("")
sleep(3)
clear()
print(Colour.grey + Style.bold + "Get ready to greet the cousins.")
print("")
sleep(4)
clear()
print(Colour.reset + Style.bold + "---------------------------------------")
print("| Maybe I'll go to the guest room...  |")
print("---------------------------------------")
print(Colour.grey + "   You think to yourself.")
sleep(3)
clear()


print(Colour.grey + Style.bold + "You decide to spend your computer time playing your favourite game.")
sleep(5)
clear()
print("   .____________________________________________________________________________.")
print("   |.--------------------------------------------------------------------------.|")
print("   ||                                                      ,-,-.               ||") 
print("   ||                                                         _(    _)         ||") 
print("   ||                                                        (__,`-'           ||") 
print("   ||                                              ,'`.   .-----,              ||") 
print("   ||                               __           ,','`.`.  |   |               ||") 
print("   ||                    _____    ,'  `.       ,','    `.`.|---|               ||") 
print("   ||                _,-'     \  /      \    ,',' _____  `.`.  |               ||") 
print("   ||             ,-'          \ \      /  ,','  |  |  |   `.`.|               ||") 
print("   ||           ,'           ___\ `.__.' ,','__  |--|--|   __'.`.              ||") 
print("   ||          /         _,-'     .----. \|    \ |__|__|  /    |/      ,-' \   ||") 
print("   ||         |        ,'         |    |  |     \        /     |    ,-'    _\  ||") 
print("   ||         |        |          |    |  |      \      /      |  ,'    ,-'    ||") 
print("   ||          \       \          |    |  |       \    /       | /     /       ||") 
print("   ||            \       `.       |    |  |         \/         |  \    \       ||") 
print("   ||   ____ _    `.       `.     |    |  |    \          /    |   `.   `.     ||") 
print("   ||  '-..-'||     `.       `.   |    |  |    |\        /|    |     `.   `.   ||") 
print("   ||    ||  ||__   __`.       \  |    |  |    | \      / |    |       \    \  ||") 
print("   ||    ||  |.-.\ /__\ \       \ |    |  |    |  \    /  |    |      ,'    /  ||") 
print("   ||    ||  |   | \   ,'       / |    |  |    |          |    |    \     ,-'  ||")  
print("   ||          ____,-'        ,'  |____|  |    |          |    |     \_,-'     ||")             
print("   ||          ;             ;            |____|          |____|               ||") 
print("   ||           \       _,-'                                                   ||") 
print("   ||            \___,-'                                                       ||") 
print("   ||                                                                          ||") 
print("   ||_ ________________________________________________________________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print(" /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("|.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-| ")
print("/____________________________/_______________________\_____________________o________\ ")
print("\___________________________________________________________________________________/ ")

sleep(3)
clear()

print("   .____________________________________________________________________________.")
print("   |.--------------------------------------------------------------------------.|")
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||               _     ____  ____  ____  _  _      _____                    ||") 
print("   ||              / \   /  _ \/  _ \/  _ \/ \/ \  /|/  __/                    ||") 
print("   ||              | |   | / \|| / \|| | \|| || |\ ||| |  _                    ||") 
print("   ||              | |_/\| \_/|| |-||| |_/|| || | \||| |_//                    ||") 
print("   ||              \____/\____/\_/ \|\____/\_/\_/  \|\____\                    ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||               " + Colour.yellow + "█████████████████░░░░░░░░░░░░░░░░░ 50%" + Colour.reset + "                     ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||  ####  # #    #   #### #    #                                            ||")  
print("   || #      # ##  ## #      #    #                                            ||")             
print("   ||  ####  # # ## #  ####  #    #                                            ||") 
print("   ||      # # #    #      # #######                                           ||") 
print("   || #    # # #    # #    #      #                                            ||") 
print("   ||  ####  # #    #  ####       #                                            ||") 
print("   ||_ ________________________________________________________________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print(" /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("|.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-| ")
print("/____________________________/_______________________\_____________________o________\ ")
print("\___________________________________________________________________________________/ ")


sleep(3)
clear()

print("   .____________________________________________________________________________.")
print("   |.--------------------------------------------------------------------------.|")
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||               _     ____  ____  ____  _  _      _____                    ||") 
print("   ||              / \   /  _ \/  _ \/  _ \/ \/ \  /|/  __/                    ||") 
print("   ||              | |   | / \|| / \|| | \|| || |\ ||| |  _                    ||") 
print("   ||              | |_/\| \_/|| |-||| |_/|| || | \||| |_//                    ||") 
print("   ||              \____/\____/\_/ \|\____/\_/\_/  \|\____\                    ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||               " + Colour.yellow + "████████████████████████████████▓ 99%" + Colour.reset + "                      ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||  ####  # #    #   #### #    #                                            ||")  
print("   || #      # ##  ## #      #    #                                            ||")             
print("   ||  ####  # # ## #  ####  #    #                                            ||") 
print("   ||      # # #    #      # #######                                           ||") 
print("   || #    # # #    # #    #      #                                            ||") 
print("   ||  ####  # #    #  ####       #                                            ||") 
print("   ||_ ________________________________________________________________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print(" /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("|.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-| ")
print("/____________________________/_______________________\_____________________o________\ ")
print("\___________________________________________________________________________________/ ")

sleep(3)
clear()


print("   .____________________________________________________________________________.")
print("   |.--------------------------------------------------------------------------.|")
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||" + Colour.blue + "              ###               ###   # ##   # ##    ###   # ##" + Colour.reset + "           ||") 
print("   ||" + Colour.blue + "      ###    ##               #   #  ##  #  ##  #  #   #  ##  ##" + Colour.reset + "          ||")
print("   ||" + Colour.blue + "      ##   ##                 #####  #      #      #   #  #" + Colour.reset + "               ||") 
print("   ||" + Colour.blue + "          ###                 #      #      #      #   #  #" + Colour.reset + "               ||") 
print("   ||" + Colour.blue + "   ##     ##                   ###   #      #       ###   #" + Colour.reset + "               ||") 
print("   ||" + Colour.blue + "   ##     ##" + Colour.reset + "                                                              ||") 
print("   ||" + Colour.blue + "         ###                   404 error-" + Colour.reset + "                                 ||") 
print("   ||" + Colour.blue + "          ###                  program 'SIMS4CODEFILE!1'" + Colour.reset + "                  ||") 
print("   ||" + Colour.blue + "           ###                 ran into an error, the file is not" + Colour.reset + "         ||") 
print("   ||" + Colour.blue + "                                responding." + Colour.reset + "                               ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||" + Colour.blue + "                              Try loading again later." + Colour.reset + "                    ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||")  
print("   ||                                                                          ||")             
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||                                                                          ||") 
print("   ||_ ________________________________________________________________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print(" /.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("|.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-.-| ")
print("/____________________________/_______________________\_____________________o________\ ")
print("\___________________________________________________________________________________/ ")

sleep(6)
clear()     

print("As the game file is broken, you instead watch cartoons on the laptop." + Colour.reset)
sleep(2)
clear()
print("   ._____________________.")
print("   |.-------------------.|")
print("   ||" + Colour.yellow + "  |\/\/\/|" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |      |" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |      |" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |" + Colour.reset + " (o)(o)" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |     _)" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  | ,___|" + Colour.reset + "          ||")
print("   ||" + Colour.yellow + "  |   /" + Colour.reset + "            ||")
print("   ||" + Colour.yellow + " /____\ " + Colour.reset + "           ||")
print("   ||" + Colour.yellow + "/      \ " + Colour.reset + "          ||")
print("   ||_ _________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.\ ")
print("/.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("/______/__________\___o_____\ ")
print("\___________________________/ ")
sleep(2)
clear()
print("   ._____________________.")
print("   |.-------------------.|")
print("   ||" + Colour.yellow + "  |\/\/\/|" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |      |" + Colour.reset + " D O H   ||")
print("   ||" + Colour.yellow + "  |      |" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |" + Colour.reset + " (-)(-)" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  |     _)" + Colour.reset + "         ||")
print("   ||" + Colour.yellow + "  | ,___|" + Colour.reset + "          ||")
print("   ||" + Colour.yellow + "  |   /" + Colour.reset + "            ||")
print("   ||" + Colour.yellow + " /____\ " + Colour.reset + "           ||")
print("   ||" + Colour.yellow + "/      \ " + Colour.reset + "          ||")
print("   ||_ _________________||")
print("   /.-.-.-.-.-.-.-.-.-.-.\ ")
print("  /.-.-.-.-.-.-.-.-.-.-.-.\ ")
print("/.-.-.-.-.-.-.-.-.-.-.-.-.-\ ")
print("/______/__________\___o_____\ ")
print("\___________________________/ ")


label .nathan
sleep(3)
clear()
print(Style.bold + Colour.grey + "You hear someone enter the room." + Colour.reset) 
  

sleep(3)
clear()
print("///-\\\ ")
print("|^   ^| ")
print("|O   O| ")
print("|  ~  |")
print(" \ - /")
print("  | |")
print("/     |")
sleep(3)
clear()

print("///-\\\ ")
print("|^   ^| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + " Im nathan." + Colour.reset)
print(" \ 0 /")
print("  | |")
print("/     |")
sleep(3)
clear()

print("///-\\\ ")
print("|-   ^| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : and you are?" + Colour.reset)
print(" \ - /")
print("  | |")
print("|     |")
sleep(3)
clear()

print("")
name = input("Enter your name:  ")
sleep(1)
clear()

print("///-\\\ ")
print("|^   ^| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  " + name + " ?  hmm.. Sounds familar." + Colour.reset)
print(" \ 0 /")
print("  | |")
print("/     |")
sleep(2)
clear()

label .Nathan
clear()
print("///-\\\ ")
print("|^   ^| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan: Your my second cousin right? " + Colour.reset)
print(" \)- /")
print("  | |")
print("/     |")
sleep(2)

print("")
print("")
print( "Note : This is the " + Highlight.blue + "first" + Colour.reset + " choice of the game.")
sleep(2)
print("")
print("What will your choice be, " + name + " ?" + Colour.reset)
#CHOICE 2, TWO ANSWERS
nat = input("Yes/No: ")
sleep(1)
clear()

if nat == "No" :
    print("///-\\\ ")
    print("|^   -| ")
    print("|O   O| " + Colour.green + Style.bold + "  Nathan : Your Funny. " + Colour.reset)
    print("|  ~  |")
    print(" \ o /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    goto .afternathanyn
    
if nat == "Yes" :
    print("///-\\\ ")
    print("|^   -| ")
    print("|O   O| " + Colour.green + Style.bold + "  Nathan : Thought so. " + Colour.reset)
    print("|  ~  |")
    print(" \ o /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    goto .afternathanyn
    
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .Nathan

    
label .afternathanyn
print("///-\\\ ")
print("|'   '| ")
print("|O   O| " + Colour.green + Style.bold + "  Nathan : ... " + Colour.reset)
print("|  ~  |")
print(" \ - /")
print("  | |")
print("/     |")
sleep(3)
clear()    
    
    
print("///-\\\ ")
print("|'   '| ")
print("|O   O| " + Colour.green + Style.bold + "  Nathan : I stole some food from downstairs. " + Colour.reset)
print("|  ~  |")
print(" \ > /")
print("  | |")
print("/     |")
sleep(3)
clear()    

label .hungry 
clear()
print("///-\\\ ")
print("|-   -| ")
print("|O   O| " + Colour.green + Style.bold + "  Nathan : Hungry? " + Colour.reset)
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("/     |")
sleep(3)
clear()      
    
print(Colour.grey + Style.bold + "Accept food from Nathan, " + name + " ?" + Colour.reset)
fod = input("Yes/No: ")
#CHOICE 3, TWO ANSWERS

if fod == "Yes" :
    clear()
    print("///-\\\ ")
    print("|-   -| ")
    print("|o   o| " + Colour.green + Style.bold + "  Nathan : Here, " + Colour.reset)
    print("|  ~  |")
    print(" \ > /")
    print("  | |")
    print("/     |")
    sleep(2)
    clear()
    print(Colour.magenta + "                     ____")
    print("          ___      .' /:::.      ___")
    print("          \   -.  /  (:::-'\  .-   / ")
    print("           >_-=.\/:\__\/__  \/.=-_<")
    print("           > -='/\::::/\:::\/\'=- <")
    print("          /__.-'  \::'  )::/  '-.__\ ")
    print("                   '.__/::' " + Colour.reset)
    sleep(2)
    clear()
    print("///-\\\ ")
    print("|-   -| ")
    print("|-   -| " + Colour.green + Style.bold + "  Nathan : You're Lucky. Thats the best flavour. " + Colour.reset)
    print("|  ~  |")
    print(" \ 0 /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    goto .comflash


if fod == "No" :
    clear()
    print("///-\\\ ")
    print("|-   -| ")
    print("|o   o| " + Colour.green + Style.bold + "  Nathan : Oh. " + Colour.reset)
    print("|  ~  |")
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(2)
    clear() 
    print("///-\\\ ")
    print("|-   -| ")
    print("|=   =| " + Colour.green + Style.bold + "  Nathan : More for me I guess. " + Colour.reset)
    print("|  ~  |")
    print(" \ _ /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    goto .comflash

clear()
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .hungry

label .comflash
clear()
print("///-\\\ ")
print("|^   -| ")
print("|O   O| " + Colour.green + Style.bold +  name + "?" + Colour.reset)
print("|  ~  |")
print(" \ o /")
print("  | |")
print("/     |")
sleep(2)
clear()

print("///-\\\ ")
print("|-   -| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Why's your computer flashing?" + Colour.reset)
print(" \ . /")
print("  | |")
print("|     |")
sleep(3)
clear()


print("                         ______ ")                    
print(" _________        .---          ---.   ")            
print(":______.-':      :  .--------------.  : ")            
print("| ______  |      | :                : | ")            
print("|:______B:|      | |" + Colour.red + "  EMERGENCY" + Colour.reset + "   : | | ")            
print("|:______B:|      | |                | | ")            
print("|:______B:|      | |                | | ")            
print("|         |      | |                | | ")            
print("|:_____:  |      | |                | | ")            
print("|    ==   |      | :                : | ")            
print("|       O |      :  '--------------'  :  ")           
print("|       o |      :'---...______...---'  ")            
print("|       o |-._.-i___/'             \._ ")             
print("|'-.____o_|   '-.   '-...______...-'  `-._ ")         
print(":_________:      `.____________________   `-.___.-.") 
print("                 .'.eeeeeeeeeeeeeeeeee.'.      :___:")
print("              .'.eeeeeeeeeeeeeeeeeeeeee.'. ")        
print("              :____________________________:")
sleep(3)
clear()

print("                         ______ ")                    
print(" _________        .---          ---.   ")            
print(":______.-':      :  .--------------.  : ")            
print("| ______  |      | :                : | ")            
print("|:______B:|      | |" + Colour.red + "  EMERGENCY" + Colour.reset + "   : | | ")            
print("|:______B:|      | |  zombies.      | | ")            
print("|:______B:|      | |defend yourself.| | ")            
print("|         |      | | seek shelter.  | | ")            
print("|:_____:  |      | |                | | ")            
print("|    ==   |      | :                : | ")            
print("|       O |      :  '--------------'  :  ")           
print("|       o |      :'---...______...---'  ")            
print("|       o |-._.-i___/'             \._ ")             
print("|'-.____o_|   '-.   '-...______...-'  `-._ ")         
print(":_________:      `.____________________   `-.___.-.") 
print("                 .'.eeeeeeeeeeeeeeeeee.'.      :___:")
print("              .'.eeeeeeeeeeeeeeeeeeeeee.'. ")        
print("              :____________________________:")
sleep(3)
clear()





print("///-\\\ ")
print("|^   ^| ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : oh god." + Colour.reset)
print(" \ ' /")
print("  | |")
print("/     |")
sleep(3)
clear()


print("///-\\\ ")
print("|     | ")
print("|O   O| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : whats that noise.." + Colour.reset)
print(" \ . /")
print("  | |")
print("|     |")
sleep(3)
clear()


label .Bedroom
print("")
print("")
print("")
print("      ()___") 
print("    ()//__/)_________________()")
print("    ||(___)//#/_/#/_/#/_/#()/||")
print("    ||----|#| |#|_|#|_|#|_|| ||")
print("    ||____|_|#|_|#|_|#|_|#||/||")
print("    ||    |#|_|#|_|#|_|#|_||      ")
sleep(1)
clear()

print("")
print("")
print(Colour.red + "                   *BANG*" + Colour.reset)
print("      ()___ ")
print("    ()//__/)_________________()")
print("    ||(___)//#/_/#/_/#/_/#()/||")
print("    ||----|#| |#|_|#|_|#|_|| ||")
print("    ||____|_|#|_|#|_|#|_|#||/||")
print("    ||    |#|_|#|_|#|_|#|_||      ")
sleep(0.5)

clear()
print("")
print("")
print("")
print("      ()___ ")
print("    ()//__/)_________________()")
print("    ||(___)//#/_/#/_/#/_/#()/||")
print("    ||----|#| |#|_|#|_|#|_|| ||")
print("    ||____|_|#|_|#|_|#|_|#||/||")
print("    ||    |#|_|#|_|#|_|#|_||      ")
sleep(2)
clear()

print("")
print("")
print(Colour.red + "                   *BANG*" + Colour.reset)
print("      ()___ ")
print("    ()//__/)_________________()")
print("    ||(___)//#/_/#/_/#/_/#()/||")
print("    ||----|#| |#|_|#|_|#|_|| ||")
print("    ||____|_|#|_|#|_|#|_|#||/||")
print("    ||    |#|_|#|_|#|_|#|_||      ")
sleep(0.5)
clear()



print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : We should get moving... " + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Which room should we go to " + name + "?" +  Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | " + Colour.red + "*BANG*" + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ ' /")
print("  | |")
print("|     |")
sleep(1)
clear()
print("///-\\\ ")
print("|     | ")
print("|0   0| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : QUICK!!" + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")



sleep(2)
clear()
label .not_safe_br
clear()
print(Colour.green + Style.bold + "Nathan : Which room should we go to?" + Colour.reset)
sleep(3)
clear()
print(Colour.green + Style.bold + "Our choices are Kitchen, Basement, Laundry or Bathroom." + Colour.reset)
sleep(2)
#CHOICE 4, FOUR ANSWERS

whereto = input("Where would you like to go: ")
if whereto == "Kitchen":
    goto .Kitchen
if whereto == "Basement":
    goto .Basement
if whereto == "Bathroom":
    goto .Bathroom
if whereto == "Laundry":
    goto .Laundry

clear()    
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .not_safe_br


#Kitchen scene

label .Kitchen
clear()
print(Colour.reset + "Your eyes dart around the kitchen.")
sleep(2)
clear()
print("")
print("")
print("                                  \ \ \ ")
print("        ____               ________```")
print("        \  =|-            [________] \ ")
print("        |  =| |     _     |        |  \           __")
print("        |__=|-  O--(_)    `.______.'   \ O=======(__)")
print("               /|\ ")
print("             (/(|(\                                          |")
print("_____________________________________________________________|")
sleep(2)
clear()

print("   .-.    .-.    .-.    .-.  .-.  .---.  .-.      .--.      .-.  .--. ")
print("  <   |  <   |  <   |   | |  | |  | | |  | |      |()|     /  |  |  | ")
print("   )  |   )  |   )  |   | |  | |  | | |  | |      |  |     |  |  |  | ")
print("   )()|   )()|   )()|   |o|  | |  | | |  | |      |  |     |  |  |()| ")
print("   )()|   )()|   )()|   |o|  | |  | | |  | |      |  |     |  |  |()| ")
print("  <___|  <___|  <___|   |\|  | |  | | |  | |      |  |     |  |  |__| ")
print("   }  |   || |   =  |   | |  | |  `-|-'  | |      |  |     |  |  |   L ")
print("   }  |   || |   =  |   | |  | |   /A\   | |      |  |     |  |  |   J ")
print("   }  |   || |   =  |   |/   | |   |H|   | |      |  |     |  |  |    L ")
print("   }  |   || |   =  |        | |   |H|   | |     _|__|_    |  |  |    J ")
print("   }  |   || |   =  |        | |   |H|   | |    | |   |    |  |  | A   L ")
print("   }  |   || |   =  |        | |   \V/   | |    | |   |     \ |  | H   J ")
print("   }  |   FF |   =  |        | |    -    | |    | \   |      ,Y  | H A  L ")
print("   }  |   LL |    = |       _F J_       _F J_   \  `--|       |  | H H  J ")
print("   }  |   LL |     \|     /       \   /       \  `.___|       |  | H H A L ")
print("   }  |   \\ |           J         L |  _   _  |              |  | H H U J ")
print("   }  |    \\|           J         F | | | | | |             /   | U |.-' ")
print("    } |     \|            \       /  | | | | | |    .-.-.-.-/    |_.-' ")
print("     \|                    `-._.-'   | | | | | |   ( (-(-(-( ) ")
print("                                     `-' `-' `-'    `-`-`-`-'")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : welcome to the kitchen." + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : I'm actually quite a good cook..." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ [ /")
print("  | |")
print("|     |")
sleep(3)
clear()

print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Not to brag but I've won quite a few awards.." + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ > /")
print("  | |")
print("|     |")

sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Such as the wellington wish, " + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()

print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : and the -" + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ > /")
print("  | |")
print("|     |")
sleep(3)
clear()

print("///-\\\ ")
print("|     | " + Colour.red + "*BANG*" + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ ' /")
print("  | |")
print("|     |")
sleep(1)
clear()
print("///-\\\ ")
print("|     | ")
print("|0   0| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : I dont think we're safe here either." + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")

sleep(3)
clear()
label .kitchenques
print(Colour.green + Style.bold + "Nathan : We can to the Bedroom, Laundry, out the Window, or investigate the Cabinets.")
sleep(2)
#CHOICE 5, FOUR ANSWERS
print(Colour.reset + "HINT - enter as such [Bedroom, Laundry, Window, Cabinets]")
print("")
sleep(2)

whereto = input(Colour.green + Style.bold + "Where would you like to go : " + Colour.reset)
if whereto == "Bedroom":
  goto .game_over
  
if whereto == "Window":
  goto .escape_card
  
if whereto == "Laundry":
  goto .Laundry
  
if whereto == "Cabinets":
  goto .cabinets

clear()  
print(Colour.reset + "Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .kitchenques



label .Laundry
sleep(2)
clear()
print(Colour.reset + "")
print("")
print("                                                        |\ ")
print("                                                        | \ ")
print("                                                        |")
print("              ____________    ____________              |")
print("             / O * maytag \  / O O maytag \             |")
print("             |____________|  |____________|             |")
print("            | ____________ ||              |            |")
print("            ||            |||              |            |")
print("            ||           ]|||              |            |")
print("   /\  ____ ||            |||              |  _______   |")
print(" [|  ||" + Colour.blue + "Tide" + Colour.reset + "|||____________|||              |  |#####|   |")
print("__|__||____||______________||______________|__|#####|___|")
print("                                              |#####| ")
sleep(2)
clear()
print('''   ______________ 
 /'              |
(                |
 \.______________|
    \\. //\\ .// 
    `\\.  .//.  
    // `\\//  \\ 
   ||  .//\\.  ||
   ||.//   `\\.||
   |//       `\\|
   ''          ``''')
sleep(2)
clear()
print("  ||")
print("  ||")
print("  ||")
print("  ||")
print("  ||")
print("  ||")
print("  || ")    
print("  ||  ")   
print(" /||\ ")
print("/||||\ ")
print("======         __|__")
print("||||||        / ~@~ \ ")
print("||||||       |-------| ")
print("||||||       |_______|")

sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : welcome to the laundry." + Colour.reset)
print("|=   =| ")
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Theres not much here, really." + Colour.reset)
print("|.   .| ")
print("|  ~  |")
print(" \ - /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : We seem safe though." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : So...." + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ o /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : yknow..." + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ o /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : I dont know you well." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ - /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : But you seem cool." + Colour.reset)
print("|u   u| ")
print("|  ~  |")
print(" \ - /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|-   ^| " + Colour.green + Style.bold + "  Nathan : Whats your Favourite colour?." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ ^ /")
print("  | |")
print("|     |")
sleep(3)
clear()
colour = input("Enter your favourite colour : ")
clear()
print("///-\\\ ")
print("|-   ^| ")
print("|o   o| ")
print("|  ~  |")
print(" \ - /")
print("  | |")
print("|     |")
sleep(0.5)
clear()
print("///-\\\ ")
print("|-   -| ")
print("|o   o| ")
print("|  ~  |")
print(" \ o /")
print("  | |")
print("|     |")
sleep(0.5)
clear()
print("///-\\\ ")
print("|-   -| " + Colour.green + Style.bold + "  Nathan : Weird.." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : " + colour + " is my favourite too." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ > /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Im bored" + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ > /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Lets go somewhere else." + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ , /")
print("  | |")
print("|     |")
sleep(2)
clear()

label .launques
sleep(2)
clear()
print(Colour.green + Style.bold + "We can go to the Kitchen, Basement, Bathroom or Stay.")
sleep(2)
#CHOICE 6, FOUR ANSWERS
kitchenans = input("Whats your choice?: " + Colour.reset)
sleep(3)

if kitchenans == "Kitchen":
    clear()
    goto .Kitchen

if kitchenans == "Basement":
    clear()
    goto .Basement

if kitchenans == "Bathroom":
    clear()
    goto .Bathroom
    
if kitchenans == "Stay":
    clear()
    goto .game_over

clear()    
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .launques    
    
clear()
print(Colour.green + Style.bold + " Nathan : good choice." + Colour.reset)
sleep(2)
clear()

#Cabinet scene

label .cabinets
clear()
print(Colour.reset)
print(" _______")
print("|_o_|_o_|")
print("|___o___|")      
print("|___o___|")      
print("|___o___|")
print(" ||   || ")
print("")
sleep(3)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : I do wonder whats inside..." + Colour.reset)
print("|$   $| ")
print("|  ~  |")
print(" \ p /")
print("  | |")
print("|     |")
sleep(3)
clear()

#Cabinet choice

print(Colour.green + Style.bold + "  Nathan : We only have room for one...")
sleep(3)
print("Pick. WISELY.")
sleep(2)
print("or not.")
sleep(1)
print("its your choice, I suppose.")
sleep(2)
clear()
label .kak
print("Knife. Apple. Key. or.. Nothing." + Colour.reset)
print("") 
print("  ,--./,-.       ") 
print(" / #      \    ___________ ____________") 
print("|          |  |           )._______.-'  ") 
print(" \        /    `----------'") 
print("  `._,._,'") 
print("  ") 
print("          ooo,    .---.") 
print("         o`  o   /    |\________________") 
print("        o`   'oooo()  | ________   _   _)") 
print("        `oo   o` \    |/        | | | |") 
print("          `ooo'   `---'          -  |_|") 
print("")
sleep(2)
#CHOICE 7, FOUR ANSWERS
item = input(Colour.green + Style.bold + "Nathan : Whats your choice " + name + "?   :  " + Colour.reset)


if item == "Nothing":
    clear()
    print(Colour.green + Style.bold + "  Nathan : good choice." + Colour.reset)
    sleep(3)
    goto .game_over

if item == "Knife":
    clear()
    print(Colour.green + Style.bold + "  Nathan : good choice." + Colour.reset)
    sleep(3)
    goto .fight_win
   
if item == "Apple":
    clear()
    print(Colour.green + Style.bold + "  Nathan : good choice." + Colour.reset)
    sleep(2)
    clear()
    print("///-\\\ ")
    print("|-   -| ")
    print("|0   0| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : wait.." + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(2)
    clear()
    print("///-\\\ ")
    print("|-   -| ")
    print("|p   p| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Im allergic to apples." + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    print("///-\\\ ")
    print("|     | ")
    print("|o   o| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : You should have it.." + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    print("///-\\\ ")
    print("|     | ")
    print("|-   -| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : You need energy to fight." + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    print("You take the apple and bite into it.")
    sleep(4)
    clear()
    print(" ,--./,-.")
    print("/,-._.--~\ ")
    print(" __}  {")
    print("\`-._,-`-,")
    print(" `._,._,' ")
    sleep(2)
    clear()
    print("///-\\\ ")
    print("|^    | ")
    print("|o   o| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Sorry to disturb..." + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    print("///-\\\ ")
    print("|     | ")
    print("|0   0| ")
    print("|  ~  |" + Colour.green + Style.bold + "  Nathan : But did you hear something??" + Colour.reset)
    print(" \ - /")
    print("  | |")
    print("/     |")
    sleep(3)
    clear()
    
    goto .game_over
   

if item == "Key":
   clear() 
   print(Colour.green + Style.bold + "  Nathan : good choice." + Colour.reset)
   sleep(3)
   clear()
   print("///-\\\ ")
   print("|_   _| ")
   print("|o   o| ")
   print("|  ~  |" + Colour.green + Style.bold + "  Nathan : This Key looks pretty old..." + Colour.reset)
   print(" \ 0 /")
   print("  | |")
   print("/     |")
   sleep(3)
   clear()
   print("///-\\\ ")
   print("|^   _| ")
   print("|o   o| ")
   print("|  ~  |" + Colour.green + Style.bold + "  Nathan : I wonder what it's for." + Colour.reset)
   print(" \ - /")
   print("  | |")
   print("/     |")
   sleep(3)
   clear()
   goto .game_over
   
   
   


clear()
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .kak   
   
#After knife
   
label .fight_win
clear()
sleep(1)
print(Colour.green + Style.bold + "..." + Colour.reset)
sleep(2)
clear()
print("               ...... ")              
print("            .:||||||||:.  ")          
print("           /            \ ")          
print("          (" + Colour.red + "   o      o  " + Colour.reset + " ) ")         
print("--@@@@----------:  :----------@@@@--")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|0   0| ")
print("|  ~  |" + Colour.green + Style.bold + name + "?!!" + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|>   <| ")
print("|  ~  |" + Colour.green + Style.bold + "USE YOUR KNIFE!!!" + Colour.reset)
print(" \() /")
print("  | |")
print("|     |")
sleep(2)
clear()

print(Colour.red + "⠰⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠜")
print("⠀⠸⢷⣄⠠⠀⠀⠀⢠⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠋⠀⠀")
print("⠀⠀⠀⠙⢆⠀⠈⣄⢸⡄⢀⣤⢁⠄⠀⠀⠀⠀⠔⠊⠁⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠳⣤⣸⣿⣷⣿⣿⣿⠀⣀⠴⠂⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠠⢤⣀⣴⣿⣿⣿⣿⣿⣿⣿⣞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣟⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⣤⡶⠻⢿⣿⣿⣿⣿⣿⣿⣿⡿⠦⢤⣀⣀⡀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⢻⣿⣿⡿⠛⠙⠻⣏⠀⠀⠀⠈⠙⠛⠃⠀⠀⠀⠀")
print("⢀⠀⢿⠆⠀⠀⠸⡟⢹⠁⠀⠀⠀⠈⠦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠃⢸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠀⠀⠀" + Colour.reset)
sleep(1)
clear()
print("///-\\\ ")
print("|     | ")
print("|0   0| ")
print("|  ~  |" + Colour.green + Style.bold + "we survived.." + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|-   -| ")
print("|  ~  |" + Colour.green + Style.bold + "for now.." + Colour.reset)
print(" \~~ /")
print("  | |")
print("|     |")
sleep(2)
clear()
print(Colour.yellow + "You survived." + Colour.reset)
sleep(5)
clear()
goto .com_scene


#Bathroom scene   
   
label .Bathroom
clear()
print("")
print(Colour.reset + "")

sleep(1)
print("                                                         |")
print("                                            __________   |")
print("                           _    __    _    |          |  |")
print("                          /_\  /  \  /_\   |          |  |")
print("                          =|= | // | =|=   |          |  |")
print("                           !   \__/   !    |          |  |")
print("                                 _         |          |  |")
print(" ___               ___          //'        |          |  |")
print("[___]       _   :=|   |=:   __T_||_T__     |p=        |  |")
print("|  ~|     =)_)=   |   |    [__________]    |          |  |")
print("|   |      (_(    |xXx|     \_      _/     |          |  |")
print("|   |      )_)                \    /       |          |  |")
print("\___|                          |  |        |          |  |")
print(" |  `========,                 |  |        |          |  |")
print("__`.        .'_________________|  |________|__________lc_|")
print("    `.    .'                  (____)                      \ ")
print("    _|    |_...             .;;;;;;;;.                     \ ")
print("   (________);;;;          :;;;;;;;;;;:")
print("        :::::::'            '::::::::'")
sleep(5)

clear()
print("                       ___")
print("                     .' _ '.")
print("                    / /` `\ \ ")
print("                    | |   [__]")
print("                    | |" +   Colour.blue + "    {" + Colour.cyan + "{" + Colour.reset)
print("                    | |" +   Colour.blue + "    }}" + Colour.reset)
print("                 _  | |  _" +   Colour.blue + " {{" + Colour.reset)
print("     ___________<_>_| |_<_>" +   Colour.blue + "}" + Colour.cyan + "}" + Colour.reset + "________")
print("         .=======^=(___)=^=" +   Colour.blue + "{{" + Colour.reset + "====.")
print("        / .----------------" +   Colour.blue + "}" + Colour.cyan + "}" + Colour.reset + "---. \ ")
print("       / /                 " +   Colour.blue + "{{" + Colour.reset + "    \ \ ")
print("      / /                  " +   Colour.blue + "}}" + Colour.reset + ""    \ \ ")
print("     (  '========================='  ) ")
print("   '----------------------------------'")
sleep(1)

clear()
print("                       ___")
print("                     .' _ '.")
print("                    / /` `\ \ ")
print("                    | |   [__]")
print("                    | |" +   Colour.blue + "    }}" + Colour.reset)
print("                    | |" +   Colour.blue + "    {" + Colour.cyan + "{" + Colour.reset)
print("                 _  | |  _" +   Colour.blue + " }}" + Colour.reset)
print("     ___________<_>_| |_<_>" +   Colour.blue + "{{" + Colour.reset + "________")
print("         .=======^=(___)=^=" +   Colour.blue + "}}" + Colour.reset + "====.")
print("        / .----------------" +   Colour.cyan + "{" + Colour.blue + "{" + Colour.reset + "---. \ ")
print("       / /                 " +   Colour.blue + "}}" + Colour.reset + "    \ \ ")
print("      / /                  " +   Colour.blue + "{{" + Colour.reset + ""    \ \ ")
print("     (  '========================='  ) ")
print("   '----------------------------------'")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : This is the Bathroom." + Colour.reset)
print(" \ v /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : somehow the tap still works..." + Colour.reset)
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Maybe we could climb out the window?." + Colour.reset)
print(" \ . /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("You glance out the window, greeted by a beautiful view.")
sleep(5)
clear()
print('''
                                      __
                 ,-_                  (`  ).
                 |-_'-,              (     ).
                 |-_'-'           _(        '`.
        _        |-_'/        .=(`(      .     )
       /;-,_     |-_'        (     (.__.:-`-_.'
      /-.-;,-,___|'          `(       ) )
     /;-;-;-;_;_/|\_ _ _ _ _   ` __.:'   )
        x_( __`|_P_|`-;-;-;,|        `--'
        |\ \    _||   `-;-;-'
        | \`   -_|.      '-'
        | /   /-_| `
        |/   ,'-_|  \
        /____|'-_|___\
 _..,____]__|_\-_'|_[___,.._
'                          ``'--,..,. ''')     
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|-   -| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Its jammed..." + Colour.reset)
print(" \ ' /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|x   x| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Damn." + Colour.reset)
print(" \ . /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|-   -| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : theres not much else here..." + Colour.reset)
print(" \ n /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Lets go try another room.." + Colour.reset)
print(" \ - /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|-   -| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : We can go to the laundry, out the window, basement, or stay.." + Colour.reset)
print(" \ O /")
print("  | |")
print("|     |")
sleep(3)
#CHOICE 8, FOUR ANSWERS
clear()
label .bathques
print(Colour.green + Style.bold + "laundry, window, basement, stay.")

bathwhere = input("What's your choice:  " + Colour.reset)

if bathwhere == "laundry":
    goto .Laundry

if bathwhere == "window":
    goto .escape_card 

if bathwhere == "basement":
    goto .Basement
    
if bathwhere == "stay":
    goto .game_over
    
clear()
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .bathques


#Window scene

label .escape_card
clear()
print("")
print(Style.bold + Colour.grey + "You glance out the window, preparing crawl out." + Colour.reset)
sleep(3)
clear()

print("")    
print("|.------------------------------------------------------------------.|")
print("||               					            ||")
print("||              " + Colour.yellow +"|" + Colour.reset + "	                                            ||")
print("||      " + Colour.yellow + ".       |       /" + Colour.reset + "	                                    ||")
print("||       " + Colour.yellow + "\      I      /" + Colour.reset + "                                            ||")
print("||        " + Colour.yellow + "\           /" + Colour.reset + "                                             ||")
print("||         " + Colour.yellow + "\   ,g88R" + Colour.reset + "                                                ||")
print("||           " + Colour.yellow + "d888" + Colour.reset + "(`  ).                                             ||")
print("||   " + Colour.yellow + "-  --== 888" + Colour.reset + "(     )." + Colour.yellow + "=--" + Colour.reset + "           .+(`  )`.                     ||")
print("||              _                                                   ||")
print("||)         Y8P(       '`.          :(   .    )                     ||")
print("||        .+(`(      .   )     .--  `.  (    ) )                    ||")
print("||       ((    (..__.:'-'   .=(   )   ` _`  ) )                     ||")
print("||`.     `(       ) )       (   .  )     (   )  ._                  ||")
print("||  )      ` __.:'   )     (   (   ))     `-'.:(`  )                ||")
print("||)  )  ( )       --'       `- __.'         :(      ))              ||")
print("||.-'  (_.'          .')                    `(    )  ))             ||")
print("||                  (_  )                     ` __.:'               ||")
print("||" + Colour.green + "--..,___.--,--'`,---..-.--+--.,,-,,..._.--..-._.-a:f--." + Colour.reset + "           ||")
print("'--------------------------------------------------------------------' ")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|♡  ♡| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : woah...." + Colour.reset)
print(" \ 0 /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : look at the view.." + Colour.reset)
print(" \ l /")
print("  | |")
print("|     |")
sleep(2)
clear()
print("///-\\\ ")
print("|    ^| ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold  + "  Nathan : I wonder what the outside world is like.." + Colour.reset)
print(" \ - /")
print("  | |")
print("|     |")
sleep(3)
clear()
print(Colour.grey + Style.bold + "You both climb out the window." + Colour.reset) 
sleep(4)
label .carvroom
clear()
print("///-\\\ ")
print("|     | ")
print("|.   .| ")
print("|  ~  |" + Colour.green + Style.bold  + "  Nathan : shoot." + Colour.reset)
print(" \ . /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold  + "  Nathan : where do we go now?" + Colour.reset)
print(" \ . /")
print("  | |")
print("/     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : Do you know how to drive? -" + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ > /")
print("  | |")
print("|     |")
sleep(3)
clear()
print(name + "...")
sleep(3)
clear()
print("///-\\\ ")
print("|     | " + Colour.yellow + "*GROAN*" + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ ' /")
print("  | |")
print("|     |")
sleep(1)
clear()
print("///-\\\ ")
print("|     | " + Colour.green + Style.bold + "  Nathan : I guess your gonna have to-" + Colour.reset)
print("|0   0| ")
print("|  ~  |")
print(" \ . /")
print("  | |")
print("|     |")
sleep(3)
clear()
print("///-\\\ ")
print("|     | " + Colour.yellow + "*BRAINSS*" + Colour.reset)
print("|o   o| ")
print("|  ~  |")
print(" \ ' /")
print("  | |")
print("|     |")
sleep(1)
clear()
print("///-\\\ ")
print("|'   '| " + Colour.green + Style.bold + "  Nathan : LEARN!!!!!" + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ ()/")
print("  | |")
print("|     |")
sleep(2)
clear()

#Car escape scene

print("")
print("")
print("")
print("")
print(Colour.blue + "       ______")
print("      /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("     (   _    _ _\ ")
print(Colour.reset + "   `" + Colour.yellow + "   -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("   ----------------------/")
sleep(0.5)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "     ______")
print("    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("   (   _    _ _\ ")
print(Colour.reset + "   `" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("   ----------------------/")
sleep(0.5)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.reset + "  `" + Colour.yellow + " -(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("   ----------------------/")
sleep(0.5)
clear()

print("///-\\\ ")
print("|'   '| " + Colour.green + Style.bold + "  Nathan : PUNCH IT!!!!!" + Colour.reset)
print("|-   -| ")
print("|  ~  |")
print(" \ ()/")
print("  | |")
print("|     |")
sleep(3)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "    ______")
print("   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("  (   _    _ _\ ")
print(Colour.reset + "===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.3)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "      ______")
print("     /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("    (   _    _ _\ ")
print(Colour.reset + "  ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.09)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "       ______")
print("      /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("     (   _    _ _\ ")
print(Colour.reset + "   ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.08)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "        ______")
print("       /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("      (   _    _ _\ ")
print(Colour.reset + "    ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.07)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "         ______")
print("        /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("       (   _    _ _\ ")
print(Colour.reset + "     ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.06)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "           ______")
print("          /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("         (   _    _ _\ ")
print(Colour.reset + "       ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.05)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "            ______")
print("           /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("          (   _    _ _\ ")
print(Colour.reset + "        ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.04)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "             ______")
print("            /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("           (   _    _ _\ ")
print(Colour.reset + "         ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "              ______")
print("             /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("            (   _    _ _\ ")
print(Colour.reset + "          ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)

clear()
print("")
print("")
print("")
print("")
print(Colour.blue + "              ______")
print("             /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("            (   _    _ _\ ")
print(Colour.reset + "          ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "              ______")
print("             /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("            (   _    _ _\ ")
print(Colour.reset + "          ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "               ______")
print("              /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("             (   _    _ _\ ")
print(Colour.reset + "           ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                 ______")
print("                /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("               (   _    _ _\ ")
print(Colour.reset + "             ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                  ______")
print("                 /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                (   _    _ _\ ")
print(Colour.reset + "              ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                   ______")
print("                  /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                 (   _    _ _\ ")
print(Colour.reset + "               ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                    ______")
print("                   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                  (   _    _ _\ ")
print(Colour.reset + "                ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                     ______")
print("                    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                   (   _    _ _\ ")
print(Colour.reset + "                 ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                      ______")
print("                     /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                    (   _    _ _\ ")
print(Colour.reset + "                  ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                        ______")
print("                       /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                      (   _    _ _\ ")
print(Colour.reset + "                    ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                         ______")
print("                        /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                       (   _    _ _\ ")
print(Colour.reset + "                     ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                          ______")
print("                         /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                        (   _    _ _\ ")
print(Colour.reset + "                      ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                           ______")
print("                          /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                         (   _    _ _\ ")
print(Colour.reset + "                       ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                            ______")
print("                           /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                          (   _    _ _\ ")
print(Colour.reset + "                        ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                             ______")
print("                            /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                           (   _    _ _\ ")
print(Colour.reset + "                         ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                              ______")
print("                             /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                            (   _    _ _\ ")
print(Colour.reset + "                          ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                              ______")
print("                             /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                            (   _    _ _\ ")
print(Colour.reset + "                          ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                               ______")
print("                              /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                             (   _    _ _\ ")
print(Colour.reset + "                           ===`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                               ______")
print("                              /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                             (   _    _ _\ ")
print(Colour.reset + "                            ==`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                ______")
print("                               /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                              (   _    _ _\ ")
print(Colour.reset + "                             ==`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                 ______")
print("                                /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                               (   _    _ _\ ")
print(Colour.reset + "                               =`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                  ______")
print("                                 /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                (   _    _ _\ ")
print(Colour.reset + "                                =`" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                   ______")
print("                                  /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                 (   _    _ _\ ")
print(Colour.reset + "                                  `" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                    ______")
print("                                   /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                  (   _    _ _\ ")
print(Colour.reset + "                                   `" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                     ______")
print("                                    /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                   (   _    _ _\ ")
print(Colour.reset + "                                    `" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                      ______")
print("                                     /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                    (   _    _ _\ ")
print(Colour.reset + "                                     `" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.03)
clear()

print("")
print("")
print("")
print("")
print(Colour.blue + "                                       ______")
print("                                      /" + Colour.reset + "|_||_'" + Colour.blue + "\__")
print("                                     (   _    _ _\ ")
print(Colour.reset + "                                      `" + Colour.yellow + "-(_)--(_)" + Colour.blue + "-'" + Colour.reset)
print("------------------------------------------------------")
sleep(0.3)

#Car overlooking sunset

clear()
print(Colour.grey + Style.bold + "You and nathan make your way...")
sleep(2)
print("Away.")
sleep(2)
print("Anywhere away from here.")
sleep(3)
clear()
print(Colour.yellow + "        .       .        .")
print(Colour.yellow + "         .      .       .        .'   " + Colour.reset + "            .--.")
print(Colour.yellow + " '.       .     .      .       .'     " + Colour.blue + "  ________" + Colour.reset + ".'_.'" + Colour.blue + "_____.--.___")
print(Colour.yellow + "   '.      .    .     .      .'       " + Colour.reset+ " ()_() ooo" + Colour.blue + "   ~/   -.|     .-_")
print(Colour.yellow + "     '.     .   .    .     .'         " + Colour.reset + " ((((<" + Colour.blue + "____   |      |  ____ =)")
print(Colour.yellow + "       '.    .  .   .    .'       .-'  " + Colour.blue + "(__)/" + Colour.yellow + " () " + Colour.blue + "\___\_____|_/" + Colour.yellow + "()" + Colour.blue + "\__/) ")
print(Colour.yellow + ".        '   ______    .'      .-'    " + Colour.green + " __'." + Colour.yellow + "'.__.'" + Colour.green + "_________" + Colour.green + "'." + Colour.yellow + "'.__.'" + Colour.green + "____")
print(Colour.yellow + " '-.      .-~      ~-.      .-'     " + Colour.green + " /")
print(Colour.yellow + "    '-. .'            '. .-'      " + Colour.green + "__/")
print(Colour.yellow + "_      .                .      _." + Colour.green + "/")
print(Colour.yellow + " '-._ .                  . _.-'  " + Colour.green + "|")
print(Colour.yellow + "      :                  :      "+ Colour.green + "/")
print(Colour.yellow + "  .-' .                  . '-"  + Colour.green + ".'")
print(Colour.yellow + "-'     .                . . " + Colour.green + ".'")
print(Colour.yellow + "    .'  '.            .'" + Colour.green + " _.'")
print(Colour.yellow + "  .'  .'  '__________'"+ Colour.green + ".-'")
print(Colour.blue   + "~~~~~~~~~~~~~~~~~~~~~" + Colour.green + "/")
print(Colour.blue   + "~~  ~~~    ~~~ ~~ ~ " + Colour.green + "/")
print(Colour.blue   + "  ~~   ~~~~  ~~~~ ~ " + Colour.green + "/")
sleep(5)
clear()
goto .survivecard

#You survived

label .survivecard
clear()
print(Colour.yellow + "You survived." + Colour.reset)
sleep(5)
clear()
goto .com_scene


#Basement scene

label .Basement
clear()
print("///-\\\ ")
print("|-   -| ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + name + " , welcome, to the Basement." + Colour.reset)
print(" \ > /")
print("  | |")
print("/     |")
sleep(3)
clear()

print("///-\\\ ")
print("|-   -| ")
print("|x   x| ")
print("|  ~  |" + Colour.yellow + Style.bold +  "~COUGH~" + Colour.reset)
print(" \ { /")
print("  | |")
print("/     |")
sleep(3)
clear()

print("///-\\\ ")
print("|-   -| ")
print("|o   o| ")
print("|  ~  |" + Colour.green + Style.bold + "jeez.It's Dusty in here." + Colour.reset)
print(" \ > /")
print("  | |")
print("/     |")
sleep(3)
clear()

print("                   ________________  _______________")
print("                 .'               .'               .|")
print("               .'               .'               .' |")
print("             .'_______________.'______________ .'   |")
print("             | ___ _____ ___ || ___ _____ ___ |     |")
print("             ||_=_|__=__|_=_||||_=_|__=__|_=_||     |")
print("      _______||_____===_____||||_____===_____||     |")
print("    .'       ||_____===_____||||_____===_____||    .|")
print("  .'         ||_____===_____||||_____===_____||  .' |")
print(".'___________|_______________||_______________|.'   |")
print("|.----------.|.-----___-----.||.-----___-----.|     |")
print("|]          |||_____________||||_____________||     |")
print("||          ||.-----___-----.||.-----___-----.|     |")
print("||          |||_____________||||_____________||     |")
print("||          ||.-----___-----.||.-----___-----.|     |")
print("|]         o|||_____________||||_____________||     |")
print("||          ||.-----___-----.||.-----___-----.|     |")
print("||          |||             ||||_____________||     |")
print("||          |||             |||.-----___-----.|    .'")
print("|]          |||             ||||             ||  .'o)")
print("||__________|||_____________||||_____________||.'")
print("''----------'''------------------------------''")
print("            (o)                             (o)")
sleep(3)
clear()
print("///-\\\ ")
print("|-   -| ")
print("|$   $| ")
print("|  ~  |" + Colour.green + Style.bold + "Nathan : Lets check the draws!!!!" + Colour.reset)
print(" \ 0 /")
print("  | |")
print("/     |")
sleep(3)
clear()

print(Colour. orange + '''            ..ee$$$$$ee..
        .e$*""    $    ""*$e.       
      z$"*.       $         $$c
    z$"   *.      $       .P  ^$c
   d"      *      $      z"     "b
  $"        b     $     4%       ^$
 d%         *     $     P         '$
.$          'F    $    J"          $r
4L...........b....$....$...........J$
$F           F    $    $           4$
4F          4F    $    4r          4P
^$          $     $     b          $%
 3L        .F     $     'r        JP
  *c       $      $      3.      z$
   *b     J"      $       3r    dP
    ^$c  z%       $        "c z$"
      "*$L        $        .d$"
         "*$ee..  $  ..ze$P"  
             ""*******""''' + Colour.reset)
             
sleep(3)
clear()
print("///-\\\ ")
print("|^   -| ")
print("|o   .| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : I found this ball!!" + Colour.reset)
print(" \ , /")
print("  | |")
print("/     |")

sleep(3)
clear()
print("///-\\\ ")
print("|^   -| ")
print("|.   .| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Its flat though." + Colour.reset)
print(" \ , /")
print("  | |")
print("/     |")

sleep(3)
clear()
print("///-\\\ ")
print("|^   -| ")
print("|.   .| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : well that sucks" + Colour.reset)
print(" \ , /")
print("  | |")
print("/     |")

sleep(3)
clear()
print("///-\\\ ")
print("|-   -| ")
print("|.   .| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : all empty. " + Colour.reset)
print(" \ , /")
print("  | |")
print("/     |")


sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|!   !| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : whats that noise.." + Colour.reset)
print(" \ ~ /")
print("  | |")
print("/     |")


#Door bang
sleep(2)
clear()
print("")
print("            __________")
print("           |  __  __  |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |  __  __()|")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |__________|")
sleep(1)
clear()
print("")
print("            __________ " + Colour.red + "    *BANG*" + Colour.reset)
print("           |  __  __  |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |  __  __()|")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |__________|")
sleep(0.5)
clear()
print("")
print("            __________")
print("           |  __  __  |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |  __  __()|")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |__________|")
sleep(2)
clear()
print("")
print("            __________ " + Colour.red + "    *BANG*" + Colour.reset)
print("           |  __  __  |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |  __  __()|")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |  ||  | |")
print("           | |__||__| |")
print("           |__________|")
sleep(0.5)
clear()
print("///-\\\ ")
print("|-   -| ")
print("|~   ~| ")
print("|  ~  |" + Colour.green + Style.bold + " Nathan : We need to move." + Colour.reset)
print(" \~~ /")
print("  | |")
print("/     |")
sleep(2)
clear()
sleep(3)
clear()
print("///-\\\ ")
print("|     | ")
print("|~   ~| ")
print("|  ~  |" + Colour.green + Style.bold + "NOW." + Colour.reset)
print(" \ . /")
print("  | |")
print("/     |")
sleep(2)
clear()
label .baseques
print(Colour.green + Style.bold + "Nathan : Our choices are Laundry, Bathroom, Kitchen, or Bedroom..")
sleep(2)
#CHOICE 9, FOUR ANSWERS
basewhere = input("What's your choice:  " + Colour.reset)
if basewhere == "Laundry":
    goto .Laundry

if basewhere == "Kitchen":
    goto .Kitchen 

if basewhere == "Bathroom":
    goto .Bathroom
    
if basewhere == "Bedroom":
    clear()
    print(Colour.reset + "You make your way to the bedroom.")
    sleep(2)
    clear()
    goto .game_over

clear()
print("Invalid answer!")
sleep(2)
print("Remember to Answer exactly as the question displays.")
sleep(5)
goto .baseques

#Game over :(

label .game_over
clear()
print(Colour.reset + "///-\\\ ")
print("|_   _| ")
print("|.   .| ")
print("|  ~  |" + Colour.green + Style.bold +  "  Nathan : " + name + "?" + Colour.reset)
print(" \ ~ /")
print("  | |")
print("/     |")
sleep(4)
clear()
print("///-\\\ ")
print("|     | ")
print("|~   ~| ")
print("|  ~  |" + Colour.green + Style.bold + "  Nathan : Dont.. Look.. Behind..You..." + Colour.reset)
print(" \~~ /")
print("  | |")
print("/     |")
sleep(2)
clear()
print("                       _,--~~~,")
print("                       .'        `.")
print("                       |           ;")
print("                       |           :")
print("                      /_,-==/     .'")
print("                    /'`\ " + Colour.red + "*" + Colour.reset + "  ;      :  ")    
print("                  :'    `-        :  ")    
print("                  `~*,'     .     :  ")    
print("                     :__.,._  `;  :  ")    
print("                     `\'    )  '  `, ")    
print("                         \-/  '     ) ")    
print("                         :'          \ _")
print("                          `~---,-~    `,)")
print("          ___                   \     /~`\ ")
print("    \---__ `;~~~-------------~~~(| _-'    `,")
print("  ---, ' \`-._____     _______.---'         \ ")
print(" \--- `~~-`,      ~~~~~~                     `,")
print("\----      )                                   \ ")
print("\----.  __ /                                    `-")
print(" \----'` -~____  ")
print("               ~~~~~--------,.___     ")
print("                                 ```\_ ")
print("")
print("")
sleep(1)
clear()
print("                       _,--~~~,")
print("                       .'        `.")
print("                       |           ;")
print("                       |           :")
print("                      /_,-==/     .'")
print("                    /'`\ " + Colour.red + " 0" + Colour.reset + "  ;      :  ")    
print("                  :'    `-        :  ")    
print("                  `~*,'     .     :  ")    
print("                     :__.,._  `;  :  ")    
print("                     `\'    )  '  `, ")    
print("                         \-/  '     ) ")    
print("                         :'          \ _")
print("                          `~---,-~    `,)")
print("          ___                   \     /~`\ ")
print("    \---__ `;~~~-------------~~~(| _-'    `,")
print("  ---, ' \`-._____     _______.---'         \ ")
print(" \--- `~~-`,      ~~~~~~                     `,")
print("\----      )                                   \ ")
print("\----.  __ /                                    `-")
print(" \----'` -~____  ")
print("               ~~~~~--------,.___     ")
print("                                 ```\_ ")
print("")
print("")
sleep(2)
clear()
print(Colour.red + "⠰⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠜")
print("⠀⠸⢷⣄⠠⠀⠀⠀⢠⠀⠀⠀⡀⠀⠀⠀⠀⠀⠀⠀⣠⡴⠋⠀⠀")
print("⠀⠀⠀⠙⢆⠀⠈⣄⢸⡄⢀⣤⢁⠄⠀⠀⠀⠀⠔⠊⠁⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠳⣤⣸⣿⣷⣿⣿⣿⠀⣀⠴⠂⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠠⢤⣀⣴⣿⣿⣿⣿⣿⣿⣿⣞⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣟⠛⠃⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⣤⡶⠻⢿⣿⣿⣿⣿⣿⣿⣿⡿⠦⢤⣀⣀⡀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⢻⣿⣿⡿⠛⠙⠻⣏⠀⠀⠀⠈⠙⠛⠃⠀⠀⠀⠀")
print("⢀⠀⢿⠆⠀⠀⠸⡟⢹⠁⠀⠀⠀⠈⠦⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠃⢸⣷⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠘⠛⠀⠀⠀" + Colour.reset)

sleep(0.5)
clear()
print(Colour.yellow + "You died." + Colour.reset)
sleep(5)
clear()
goto .com_scene

#IN TOTAL, SIX QUESTIONS WITH FOUR ANSWERS, THREE WITH TWO ANSWERS
#9+ SCENES
